### ISSUE TITLE
ci: configure bot variables and secret 

### ISSUE THREAD

**Issue by neilime** [hoverkraft-tech/http-header-authenticator#15]
**Describe the bug**

https://github.com/hoverkraft-tech/http-header-authenticator/actions/runs/6511583589/job/17687618833

**Comment by fredleger** [comment]
humm strangely fixed in https://github.com/hoverkraft-tech/http-header-authenticator/actions/runs/6512822120

**Comment by neilime** [comment]
yes weird but as the repository is public my idea was wrong because organisation's variables and secrets are shared over all public repositories
